Celem projektu było przetestowanie klasyfikacji kampanii na podstawie wskaźników efektywności. W praktyce zastosowana etykieta została oparta na wskaźniku ROAS, dlatego model w dużej mierze odwzorowywał istniejącą regułę biznesową, a nie odkrywał całkowicie nowych zależności.

Dane wykorzystane w repozytorium są syntetyczne i zostały wygenerowane na potrzeby projektu, tak aby odzwierciedlały przykładowe wyniki kampanii marketingowych bez użycia rzeczywistych danych firmowych.

In [39]:
# pip install plotly
# pip install seaborn
# pip install tensorflow
# pip install nbformat

In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout, Dense
from tensorflow.keras.activations import elu, exponential, hard_sigmoid, linear, relu, sigmoid, softmax, tanh
from tensorflow.keras.losses import binary_crossentropy, categorical_crossentropy, logcosh, MeanSquaredError, poisson, MeanAbsoluteError
from tensorflow.keras.metrics import AUC
from tensorflow.keras.optimizers import Adadelta, Adam, Nadam, RMSprop, SGD, Ftrl
from sklearn.model_selection import train_test_split
from sklearn import datasets
from keras.datasets import reuters
from sklearn.linear_model import Perceptron
from tensorflow.keras.preprocessing.text import Tokenizer #dot. analizy tekstu
import keras
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
data = pd.read_excel("wyniki_kampanii_syntetyczne.xlsx",header=2)

In [3]:
data_clean = data.dropna()
data_clean

,Kampania,Wyświetlenia,Kliknięcia,CTR,Śr. CPC,Koszt,Konwersje,Wartość konw.,ROAS
0,Campaign_1,4231,114,0.027146,6.14,699.96,4,888.19,1.27
1,Campaign_2,3300,118,0.035951,4.65,548.70,6,223.18,0.41
2,Campaign_3,9651,315,0.032640,3.00,945.00,12,304.71,0.32
3,Campaign_4,29391,1972,0.067113,6.93,13665.96,102,2708.08,0.20
4,Campaign_5,48774,2020,0.041417,7.12,14382.40,41,2394.86,0.17
...,...,...,...,...,...,...,...,...,...
115,Campaign_116,36925,1619,0.043873,3.28,5310.32,160,21499.00,4.05
116,Campaign_117,43260,2789,0.064471,6.60,18407.40,262,67978.50,3.69
117,Campaign_118,43546,2965,0.068102,3.04,9013.60,85,9613.51,1.07
118,Campaign_119,39199,535,0.013649,6.38,3413.30,50,9043.75,2.65
119,Campaign_120,7663,637,0.083175,5.05,3216.85,23,2648.87,0.82

In [5]:
data_clean = data_clean[data_clean['Koszt'] > 0].copy()

data_clean['ROAS'] = data_clean['Wartość konw.'] / data_clean['Koszt']
data_clean['Decyzja'] = ((data_clean['ROAS'] >= 1.5)&(data_clean["Konwersje"]>=3)).astype(int)

X = data_clean[['Kliknięcia', 'Wyświetlenia', 'Śr. CPC', 'CTR', 'Konwersje']]
y = data_clean['Decyzja']

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [7]:
X

     Kliknięcia  Wyświetlenia  Śr. CPC       CTR  Konwersje
0           114          4231     6.14  0.027146          4
1           118          3300     4.65  0.035951          6
2           315          9651     3.00  0.032640         12
3          1972         29391     6.93  0.067113        102
4          2020         48774     7.12  0.041417         41
..          ...           ...      ...       ...        ...
115        1619         36925     3.28  0.043873        160
116        2789         43260     6.60  0.064471        262
117        2965         43546     3.04  0.068102         85
118         535         39199     6.38  0.013649         50
119         637          7663     5.05  0.083175         23

[120 rows x 5 columns]

In [8]:
from sklearn.preprocessing import StandardScaler

# skalowanie
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# parametry
learning_rate = 0.01
n_iters = 1000

# funkcja aktywacji
def unit_step_func(x):
    return np.where(x >= 0, 1, 0)

# uczenie
def fit(X, y):
    n_samples, n_features = X.shape
    y = np.array([1 if i > 0 else 0 for i in y])

    weights = np.zeros(n_features)
    bias = 0

    for i in range(n_iters):
        for idx, x_i in enumerate(X):
            linear_output = np.dot(x_i, weights) + bias
            y_predicted = unit_step_func(linear_output)

            update = learning_rate * (y[idx] - y_predicted)
            weights += update * x_i
            bias += update

    return weights, bias

# predykcja
def predict(X, weights, bias):
    linear_output = np.dot(X, weights) + bias
    y_predicted = unit_step_func(linear_output)
    return y_predicted

# accuracy
def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

# trening
w, b = fit(X_train, y_train)

# test
y_pred = predict(X_test, w, b)

print("Accuracy:", accuracy(y_test.values, y_pred))

Accuracy: 0.75

In [9]:
print (y.value_counts())

Decyzja
1    69
0    51
Name: count, dtype: int64

In [11]:
data_clean[data_clean['Decyzja']==0][["Kampania","Kliknięcia", "Wyświetlenia","Koszt", "Konwersje","Wartość konw.","Decyzja","ROAS"]]

,Kampania,Kliknięcia,Wyświetlenia,Koszt,Konwersje,Wartość konw.,Decyzja,ROAS
0,Campaign_1,114,4231,699.96,4,888.19,0,1.268915
1,Campaign_2,118,3300,548.70,6,223.18,0,0.406743
2,Campaign_3,315,9651,945.00,12,304.71,0,0.322444
3,Campaign_4,1972,29391,13665.96,102,2708.08,0,0.198162
4,Campaign_5,2020,48774,14382.40,41,2394.86,0,0.166513
7,Campaign_8,2298,40705,10731.66,266,7434.38,0,0.692752
12,Campaign_13,1343,26205,4055.86,41,1874.40,0,0.462146
16,Campaign_17,1478,35952,8882.78,22,1246.54,0,0.140332
18,Campaign_19,1661,42367,2292.18,28,3036.30,0,1.324634
21,Campaign_22,273,31766,1266.72,15,458.87,0,0.362251
24,Campaign_25,440,41925,1905.20,30,1780.28,0,0.934432
27,Campaign_28,1048,26113,6225.12,63,1880.17,0,0.302030
29,Campaign_30,826,20710,5104.68,23,2330.85,0,0.456610
31,Campaign_32,593,24982,2793.03,12,2922.08,0,1.046204
34,Campaign_35,41,1924,191.47,1,99.50,0,0.519664
38,Campaign_39,1121,15489,8138.46,86,2270.46,0,0.278979
39,Campaign_40,2175,40200,9048.00,188,10103.94,0,1.116704
45,Campaign_46,259,25742,880.60,6,958.68,0,1.088667
46,Campaign_47,1490,47090,7837.40,58,7436.59,0,0.948859
47,Campaign_48,1269,38255,9428.67,76,12168.76,0,1.290613
49,Campaign_50,2132,33335,8613.28,31,8046.41,0,0.934187
52,Campaign_53,1217,19720,8628.53,14,2751.19,0,0.318848
56,Campaign_57,404,13517,2759.32,25,2284.38,0,0.827878
61,Campaign_62,82,3261,172.20,4,124.31,0,0.721893
62,Campaign_63,1608,27815,7300.32,23,5663.63,0,0.775806
64,Campaign_65,309,20735,1677.87,31,2319.50,0,1.382407
65,Campaign_66,162,2501,1014.12,10,1223.58,0,1.206544
71,Campaign_72,1417,22090,8813.74,46,5304.10,0,0.601799
72,Campaign_73,450,28245,1809.00,47,1233.71,0,0.681985
79,Campaign_80,482,19678,2222.02,5,1164.75,0,0.524185
80,Campaign_81,3162,42796,21311.88,123,15240.31,0,0.715109
83,Campaign_84,2241,33984,11787.66,42,8152.64,0,0.691625
85,Campaign_86,776,35799,4011.92,14,1025.58,0,0.255633
88,Campaign_89,2470,41785,15363.40,124,6037.70,0,0.392992
90,Campaign_91,353,4521,1129.60,13,608.40,0,0.538598
91,Campaign_92,838,17838,3846.42,19,2863.48,0,0.744453
93,Campaign_94,855,21012,1957.95,17,877.41,0,0.448127
96,Campaign_97,632,28020,4544.08,62,3438.89,0,0.756785
100,Campaign_101,1128,21208,7050.00,53,1607.24,0,0.227977
101,Campaign_102,313,10320,2172.22,10,748.12,0,0.344403
102,Campaign_103,147,3746,1005.48,14,856.52,0,0.851852
105,Campaign_106,294,24729,1934.52,10,1282.40,0,0.662903
106,Campaign_107,2837,35857,16029.05,93,3103.82,0,0.193637
107,Campaign_108,2042,42993,15600.88,32,3896.61,0,0.249769
108,Campaign_109,3690,48722,18560.70,172,11674.24,0,0.628976
109,Campaign_110,1667,43913,6151.23,141,6418.04,0,1.043375
110,Campaign_111,269,14955,1716.22,7,1336.25,0,0.778601
112,Campaign_113,619,12860,4141.11,69,3210.69,0,0.775321
113,Campaign_114,72,955,356.40,2,406.68,0,1.141077
117,Campaign_118,2965,43546,9013.60,85,9613.51,0,1.066556
119,Campaign_120,637,7663,3216.85,23,2648.87,0,0.823436