In [2]:
# pip install plotly
# pip install seaborn
# pip install tensorflow
# pip install nbformat

In [3]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout, Dense
from tensorflow.keras.activations import elu, exponential, hard_sigmoid, linear, relu, sigmoid, softmax, tanh
from tensorflow.keras.losses import binary_crossentropy, categorical_crossentropy, logcosh, MeanSquaredError, poisson, MeanAbsoluteError
from tensorflow.keras.metrics import AUC
from tensorflow.keras.optimizers import Adadelta, Adam, Nadam, RMSprop, SGD, Ftrl
from sklearn.model_selection import train_test_split
from sklearn import datasets
from keras.datasets import reuters
from sklearn.linear_model import Perceptron
from tensorflow.keras.preprocessing.text import Tokenizer #dot. analizy tekstu
import keras
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [8]:
data = pd.read_excel(r"C:\Users\a.dobrowolska\OneDrive\Desktop\P\Raport kampanii.xlsx",header=2)

c:\Users\a.dobrowolska\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [9]:
data

,Stan kampanii,Kampania,Budżet,Nazwa budżetu,Typ budżetu,Kod waluty,Stan,Przyczyny stanu,Typ kampanii,Wyświetlenia,...,Etykieta,Udział w wyśw. z sieci wysz.,Współcz. konw.,Interakcje,Współczynnik interakcji,Utrata udziału w wyśw. w sieci wyszukiwania (budżet),Utrata udziału w wyśw. w sieci wyszukiwania (ranking),Widoczne wyśw.,Wizyty w sklepie,Wizyta w sklepie stacjonarnym
0,Wstrzymana,[PMAX] [MIX] [AirPods Hero Q3'25] [MP:SEM] [L:...,3000,--,Dzienny,PLN,Wstrzymany,brak informacji; kampania została wstrzymana; ...,Performance Max,0,...,promo 2025,--,0.0000,0,--,--,--,0,"0,00",0.00
1,Wstrzymana,[SEA][iSpot][GEN] Beats Promocja,333,--,Dzienny,PLN,Wstrzymany,kampania została wstrzymana; kampania zakończy...,Wyszukiwarka,0,...,ispot_beats; 15.10,--,0.0000,0,--,--,--,0,"0,00",0.00
2,Wstrzymana,[PMAX] [MIX] [JBL & HARMAN Q4] [F:MIX] [MP:SEM...,380,--,Dzienny,PLN,Wstrzymany,brak informacji; kampania została wstrzymana; ...,Performance Max,0,...,Harman,--,0.0000,0,--,--,--,0,"0,00",0.00
3,Wstrzymana,[SEA][Generic] Insta 360 snow bundle,100,--,Dzienny,PLN,Wstrzymany,kampania została wstrzymana; Wstrzymano wszyst...,Wyszukiwarka,0,...,plik budzetowy iSpot,--,0.0000,0,--,--,--,0,"0,00",0.00
4,Wstrzymana,[SEA][Generic] iPhone 8,50,--,Dzienny,PLN,Wstrzymany,brak informacji; kampania została wstrzymana,Wyszukiwarka,0,...,plik budzetowy iSpot,--,0.0000,0,--,--,--,0,"0,00",0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,Łącznie: Sieć reklamowa,NaN,NaN,NaN,NaN,PLN,NaN,NaN,Sieć reklamowa,0,...,NaN,--,0.0000,0,--,--,--,0,"0,00",0.00
850,Łącznie: Wideo,NaN,NaN,NaN,NaN,PLN,NaN,NaN,Wideo,0,...,NaN,--,0.0000,0,--,--,--,0,"0,00",0.00
851,Łącznie: Zakupy,NaN,NaN,NaN,NaN,PLN,NaN,NaN,Zakupy,0,...,NaN,--,0.0000,0,--,--,--,0,"0,00",0.00
852,Łącznie: Performance Max,NaN,NaN,NaN,NaN,PLN,NaN,NaN,Performance Max,1574623,...,NaN,0.1633,0.0075,69705,0.0443,0.0696,0.7671,0,"677,21",677.21
853,Łącznie: Wyszukiwarka,NaN,NaN,NaN,NaN,PLN,NaN,NaN,Wyszukiwarka,197177,...,NaN,0.1517,0.0051,49239,0.2497,0.5142,0.3341,0,"519,47",519.47

In [5]:
data_clean = data.dropna()
data_clean.head()

,Stan kampanii,Kampania,Budżet,Nazwa budżetu,Typ budżetu,Kod waluty,Stan,Przyczyny stanu,Typ kampanii,Wyświetlenia,...,Etykieta,Udział w wyśw. z sieci wysz.,Współcz. konw.,Interakcje,Współczynnik interakcji,Utrata udziału w wyśw. w sieci wyszukiwania (budżet),Utrata udziału w wyśw. w sieci wyszukiwania (ranking),Widoczne wyśw.,Wizyty w sklepie,Wizyta w sklepie stacjonarnym
0,Wstrzymana,[PMAX] [MIX] [AirPods Hero Q3'25] [MP:SEM] [L:...,3000,--,Dzienny,PLN,Wstrzymany,brak informacji; kampania została wstrzymana; ...,Performance Max,0,...,promo 2025,--,0.0,0,--,--,--,0,"0,00",0.0
1,Wstrzymana,[SEA][iSpot][GEN] Beats Promocja,333,--,Dzienny,PLN,Wstrzymany,kampania została wstrzymana; kampania zakończy...,Wyszukiwarka,0,...,ispot_beats; 15.10,--,0.0,0,--,--,--,0,"0,00",0.0
2,Wstrzymana,[PMAX] [MIX] [JBL & HARMAN Q4] [F:MIX] [MP:SEM...,380,--,Dzienny,PLN,Wstrzymany,brak informacji; kampania została wstrzymana; ...,Performance Max,0,...,Harman,--,0.0,0,--,--,--,0,"0,00",0.0
3,Wstrzymana,[SEA][Generic] Insta 360 snow bundle,100,--,Dzienny,PLN,Wstrzymany,kampania została wstrzymana; Wstrzymano wszyst...,Wyszukiwarka,0,...,plik budzetowy iSpot,--,0.0,0,--,--,--,0,"0,00",0.0
4,Wstrzymana,[SEA][Generic] iPhone 8,50,--,Dzienny,PLN,Wstrzymany,brak informacji; kampania została wstrzymana,Wyszukiwarka,0,...,plik budzetowy iSpot,--,0.0,0,--,--,--,0,"0,00",0.0

In [15]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# wybór cech
X = data_clean[['Kliknięcia', 'Wyświetlenia', 'Śr. CPC', 'Koszt', 'Konwersje', 'Wartość konw.']]

# skalowanie
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# klastrowanie
kmeans = KMeans(n_clusters=3, random_state=123, n_init=10)
data_clean['Cluster'] = kmeans.fit_predict(X_scaled)

# podgląd
print(data_clean[['Kampania', 'Cluster']])

                                              Kampania  Cluster
0    [PMAX] [MIX] [AirPods Hero Q3'25] [MP:SEM] [L:...        0
1                     [SEA][iSpot][GEN] Beats Promocja        0
2    [PMAX] [MIX] [JBL & HARMAN Q4] [F:MIX] [MP:SEM...        0
3                 [SEA][Generic] Insta 360 snow bundle        0
4                              [SEA][Generic] iPhone 8        0
..                                                 ...      ...
841                               [SEA] [Brand] Serwis        0
842         Generic | Produkty - iPhone [Akcesoria] OV        0
843                          Brand - Mobile - Apple_OV        0
844                                  [PLA] Philips HUE        0
845             [SEA][Brand] iPad mini Silver promocja        0

[846 rows x 2 columns]

In [17]:
data_clean[data_clean['Koszt']>0][["Kampania","Kliknięcia", "Wyświetlenia","Koszt", "Konwersje","Wartość konw.","Typ kampanii","ROAS","Cluster"]]

,Kampania,Kliknięcia,Wyświetlenia,Koszt,Konwersje,Wartość konw.,Typ kampanii,ROAS,Cluster
37,PRODUKTY [SEA] [MIX] [PERFORMANCE ISPOT] [1:on...,2716,19119,787.08,15.73,32253.48,Wyszukiwarka,40.9785,0
99,Airpods [PMAX] [MIX] [PERFORMANCE ISPOT] [1:on...,1932,113947,976.11,21.83,28709.45,Performance Max,29.4120,2
105,MAC [PMAX] [MIX] [PERFORMANCE ISPOT] [1:ong] [...,1413,70349,1088.56,1.20,3353.38,Performance Max,3.0806,2
110,[PMAX] [MIX] [PERFORMANCE ISPOT] [F:MIX] [MP:G...,400,6790,539.05,1.87,302.37,Performance Max,0.5609,0
111,IPAD [PMAX] [MIX] [PERFORMANCE ISPOT] [1:ong] ...,6521,60434,3353.00,19.05,33680.06,Performance Max,10.0447,2
112,[PMAX] [MIX] [PERFORMANCE ISPOT] [F:MIX] [MP:G...,66,752,10.25,0.00,0.00,Performance Max,0.0000,0
124,[PMAX] [MIX] [PERFORMANCE ISPOT] [F:MIX] [MP:G...,140,5610,116.62,1.00,5999.00,Performance Max,51.4395,0
141,[PMAX] [MIX] [Switch to Mac APPLE Q2 2026] [F:...,1,41,0.43,0.00,0.00,Performance Max,0.0000,0
152,[PMAX] [MIX] [Mac Hero 03.2026] [F:MIX] [MP:Go...,5265,218265,3515.02,13.46,53730.87,Performance Max,15.2861,2
202,[PMAX] [MIX] [iPhone Hero 03.2026] [F:MIX] [MP...,1930,33719,3227.42,4.77,14477.85,Performance Max,4.4859,2
221,[PMAX] [MIX] [PERFORMANCE ISPOT] [1:ong] [2:ak...,2859,85872,992.71,60.98,12537.67,Performance Max,12.6297,2
294,Imac [SEA] [MIX] [PERFORMANCE ISPOT] [1:ong] [...,326,4836,880.11,0.00,0.00,Wyszukiwarka,0.0000,2
295,[PMAX] [MIX] [PERFORMANCE ISPOT] [F:MIX] [MP:G...,456,4530,348.89,0.00,0.91,Performance Max,0.0026,0
296,APPLE WATCH [PMAX] [MIX] [PERFORMANCE ISPOT] [...,5335,62872,2583.16,9.25,33107.31,Performance Max,12.8166,2
353,[PMAX] [MIX] [PERFORMANCE ISPOT] [1:ong] [2:ma...,305,4217,100.67,0.00,0.00,Performance Max,0.0000,0
359,[PMAX] [MIX] [PERFORMANCE ISPOT] [F:MIX] [MP:G...,5112,364902,4318.36,91.17,56160.76,Performance Max,13.0051,2
378,PURE BRAND [SEA] [MIX] [PERFORMANCE ISPOT] [1:...,36587,96723,1621.31,177.81,364614.82,Wyszukiwarka,224.8890,1
402,BRAND [SEA] [MIX] [PERFORMANCE ISPOT] [1:ong] ...,3999,18793,2899.21,34.05,72887.19,Wyszukiwarka,25.1404,2
443,[MIX] [MIX] [SMB: Mac to Hero 03.2026] [F:MIX]...,4748,133470,3573.85,9.47,34019.43,Performance Max,9.5190,2
455,[PMAX] [MIX] [PERFORMANCE ISPOT] [F:MIX] [MP:G...,1481,12625,164.42,0.00,0.00,Performance Max,0.0000,0
467,[PMAX] [MIX] [PERFORMANCE ISPOT] [F:MIX] [MP:G...,185,8128,243.90,0.00,0.00,Performance Max,0.0000,0
479,Ipady [SEA] [MIX] [PERFORMANCE ISPOT] [1:ong] ...,753,8408,1168.11,2.64,8891.74,Wyszukiwarka,7.6121,2
493,[PMAX] [MIX] [SMB: iPhone Hero 03.2026] [F:MIX...,2988,56508,4757.87,8.82,44565.81,Performance Max,9.3668,2
494,IP ALL MODELS [PMAX] [MIX] [PERFORMANCE ISPOT]...,5542,116985,4910.34,25.64,75772.46,Performance Max,15.4312,2
545,iPhone 11 [SEA] [MIX] [PERFORMANCE ISPOT] [1:o...,372,4860,874.41,0.36,2094.82,Wyszukiwarka,2.3957,2
625,NON APPLE+OUTLET [PMAX] [MIX] [PERFORMANCE ISP...,2834,53188,1115.56,229.64,15453.50,Performance Max,13.8527,2
642,[PMAX] [MIX] [PERFORMANCE ISPOT] [1:ong] [2:im...,175,3352,83.22,0.00,0.00,Performance Max,0.0000,0
657,Apple Watch [SEA] [MIX] [PERFORMANCE ISPOT] [1...,4390,43185,4481.88,21.03,57207.64,Wyszukiwarka,12.7642,2
679,Macbook pro [SEA] [MIX] [PERFORMANCE ISPOT] [1...,96,1253,86.35,0.00,0.00,Wyszukiwarka,0.0000,0
737,[PMAX] [MIX] [iPad Hero 03.2026] [F:MIX] [MP:G...,3608,65398,3655.95,8.28,42563.66,Performance Max,11.6423,2
741,[MIX] [MIX] [OdNowa] [F:MIX] [MP:Google] [L:go...,2412,90853,3229.05,17.17,54073.77,Performance Max,16.7460,2
816,[PMAX] [MIX] [PERFORMANCE ISPOT] [F:MIX] [MP:G...,132,1816,58.55,0.00,0.00,Performance Max,0.0000,0